# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('null_field', models.IntegerField(null=True)),
            ],
        ),
    ]
