# Generated by Django 5.0.1 on 2024-02-04 20:07

from __future__ import annotations

import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_add_not_null_column_with_null_db_default", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="a",
            name="not_null_field_db_default_null",
            field=models.IntegerField(db_default=None, default=None, null=False),
        ),
    ]
