# Generated by Django 2.2 on 2020-01-27 17:47

from __future__ import annotations

import functools

from django.db import migrations


def backward_op(c, david, test):
    pass


def forward_op(const, arg1, arg2):
    pass


class Migration(migrations.Migration):
    dependencies = [("app_data_migrations", "0003_incorrect_arguments")]

    operations = [
        migrations.RunPython(
            functools.partial(forward_op, "constant"),
            functools.partial(backward_op, "constant"),
        )
    ]
