# Generated by Django 5.0 on 2025-10-22 11:01

from __future__ import annotations

from django.db import migrations, models


def set_slug_from_name(apps, schema_editor):
    TestModel = apps.get_model("app_mixed_runpython_operations", "TestModel")
    for obj in TestModel.objects.all():
        obj.slug = obj.name.lower().replace(" ", "-")
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app_mixed_runpython_operations", "0001_initial"),
    ]

    operations = [
        # This is BAD - mixing schema operations with RunPython
        migrations.AddField(
            model_name="testmodel",
            name="slug",
            field=models.CharField(max_length=100, default=""),
            preserve_default=False,
        ),
        migrations.RunPython(set_slug_from_name, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="testmodel",
            name="slug",
            field=models.CharField(max_length=100),
        ),
    ]
