# Generated by Django 5.0 on 2025-10-22 11:02

from __future__ import annotations

from django.db import migrations


def backfill_data(apps, schema_editor):
    TestModel = apps.get_model("app_mixed_runpython_operations", "TestModel")
    for obj in TestModel.objects.filter(slug__isnull=True):
        obj.slug = "default"
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app_mixed_runpython_operations", "0002_mixed_operations"),
    ]

    operations = [
        # This is GOOD - only RunPython operations
        migrations.RunPython(backfill_data, reverse_code=migrations.RunPython.noop),
    ]
