# Generated by Django 5.0 on 2025-10-22 11:03

from __future__ import annotations

from django.db import migrations


def update_data(apps, schema_editor):
    TestModel = apps.get_model("app_mixed_runpython_operations", "TestModel")
    for obj in TestModel.objects.all():
        obj.slug = obj.slug.upper()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("app_mixed_runpython_operations", "0003_runpython_only"),
    ]

    operations = [
        # This is GOOD - RunPython with RunSQL is fine (both are data migrations)
        migrations.RunPython(update_data, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            "UPDATE app_mixed_runpython_operations_testmodel SET name = UPPER(name);",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
