version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "David-Wobrock"
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - "David-Wobrock"
