[tox]
envlist =
    py{310,311,312,313,314}-django52
    py{312,313,314}-django60
    py{312,313,314}-django61
    lint

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
allowlist_externals = ./manage.py
commands = ./manage.py test --no-input {posargs}
extras = test
pip_pre = true
deps =
    django52: django>=5.2,<5.3
    django60: django>=6.0,<6.1
    django61: django>=6.1,<6.2

[testenv:lint]
basepython = python3.12
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[flake8]
max-line-length=110
ignore=E203,W503
