# Generated by Django 2.0.1 on 2018-01-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='new_nullable_field',
            field=models.IntegerField(null=True),
        ),
    ]
