# Generated by Django 5.2.1 on 2025-05-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rename_column_custom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a',
            old_name='field',
            new_name='renamed',
        ),
    ]
