# Generated by Django 5.2.1 on 2025-05-10 01:44

from __future__ import annotations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_rename_column_custom", "0002_rename_field_a_renamed"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RenameField(
                    model_name="a",
                    old_name="renamed",
                    new_name="renamed_safe",
                ),
            ],
        )
    ]
