# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='new_null_field',
            field=models.IntegerField(null=True),
        ),
    ]
