# Generated by Django 2.2 on 2019-07-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="A",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("int_field", models.IntegerField()),
                ("char_field", models.CharField(max_length=255)),
            ],
        )
    ]
