# Generated by Django 2.2 on 2020-06-20 15:23

from django.db import migrations, models

from django_add_default_value import AddDefaultValue


class Migration(migrations.Migration):

    dependencies = [
        ("app_make_not_null_with_lib_default", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="a",
            name="col",
            field=models.CharField(default="avalue", max_length=10),
        ),
        AddDefaultValue(model_name="a", name="col", value="avalue"),
    ]
