# Generated by Django 2.0.1 on 2018-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
