# Generated by Django 4.1.7 on 2023-03-09 21:47

from __future__ import annotations

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_create_index_concurrently_exclusive", "0001_initial"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="user",
            index=models.Index(fields=["email"], name="email"),
        ),
    ]
