# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_null_field', models.IntegerField()),
            ],
        ),
    ]
