# Generated by Django 2.0.1 on 2018-05-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_create_table_with_not_null_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_null_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nn_b', to='test_app.A')),
                ('null_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='b', to='test_app.A')),
            ],
        ),
    ]
