# Generated by Django 4.1.7 on 2023-03-09 21:47

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_create_index_exclusive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, null=True),
        ),
    ]
