# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 14:15
from __future__ import unicode_literals

from django.db import migrations

import django_migration_linter as linter

class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_create_table'),
    ]

    operations = [
        linter.IgnoreMigration(),
        migrations.RenameModel(
            old_name='A',
            new_name='B',
        ),
    ]
