# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='null_field_2',
            field=models.IntegerField(default=1),
        ),
    ]
