# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app1', '0002_a_null_field_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='a',
            name='non_null_field',
            field=models.IntegerField(null=True),
        ),
    ]
